site_name: Derrick Bule
repo_url: https://github.com/DerrickBule/DerrickBule.github.io
#site_dir: site
docs_dir: docs

nav:
  - index: index.md
  - Automation: Api Automation.md
  - Jmeter:
      - Jmeter: Jmeter.md
      - index: index.md
  - Performance: Performance.md
theme:
  name: "material"
  features:
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode