site_name: Derrick Bule
repo_url: https://github.com/DerrickBule/DerrickBule.github.io.git
docs_dir: docs

nav:
- index: index.md
- Automation: Api Automation.md
- Jmeter: Jmeter.md
- Performance: Performance.md
theme:
    name: "material"
    palette:
        primary: "blue"
        accent: "deep orange"
    language: "en"
